/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Comprehensive 52+ Chain Configuration
 * Supports EVM chains, Solana, TON, Cosmos ecosystem, and more
 */

export enum ChainType {
  EVM = "EVM",
  SOLANA = "SOLANA",
  TON = "TON",
  COSMOS = "COSMOS",
  BITCOIN = "BITCOIN",
  TRON = "TRON",
  NEAR = "NEAR",
  APTOS = "APTOS",
  SUI = "SUI",
}

export interface ChainConfig {
  id: string
  chainId: string | number
  name: string
  symbol: string
  type: ChainType
  logo: string
  rpc: string[]
  explorer: string
  moralisChain?: string
  covalentChainId?: number
  enabled: boolean
}

export const CHAIN_CONFIGS: ChainConfig[] = [
  // ========== EVM CHAINS ==========
  {
    id: "ethereum",
    chainId: "0x1",
    name: "Ethereum",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/eth.png",
    rpc: ["https://eth.llamarpc.com", "https://rpc.ankr.com/eth", "https://ethereum.publicnode.com"],
    explorer: "https://etherscan.io",
    moralisChain: "eth",
    covalentChainId: 1,
    enabled: true,
  },
  {
    id: "bsc",
    chainId: "0x38",
    name: "BNB Smart Chain",
    symbol: "BNB",
    type: ChainType.EVM,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/bnb.png",
    rpc: ["https://bsc-dataseed.binance.org", "https://bsc.publicnode.com", "https://bsc.llamarpc.com"],
    explorer: "https://bscscan.com",
    moralisChain: "bsc",
    covalentChainId: 56,
    enabled: true,
  },
  {
    id: "polygon",
    chainId: "0x89",
    name: "Polygon",
    symbol: "MATIC",
    type: ChainType.EVM,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/matic.png",
    rpc: ["https://polygon-rpc.com", "https://polygon.llamarpc.com", "https://polygon.publicnode.com"],
    explorer: "https://polygonscan.com",
    moralisChain: "polygon",
    covalentChainId: 137,
    enabled: true,
  },
  {
    id: "arbitrum",
    chainId: "0xa4b1",
    name: "Arbitrum One",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/arb.png",
    rpc: ["https://arb1.arbitrum.io/rpc", "https://arbitrum.llamarpc.com", "https://arbitrum.publicnode.com"],
    explorer: "https://arbiscan.io",
    moralisChain: "arbitrum",
    covalentChainId: 42161,
    enabled: true,
  },
  {
    id: "optimism",
    chainId: "0xa",
    name: "Optimism",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/op.png",
    rpc: ["https://mainnet.optimism.io", "https://optimism.llamarpc.com", "https://optimism.publicnode.com"],
    explorer: "https://optimistic.etherscan.io",
    moralisChain: "optimism",
    covalentChainId: 10,
    enabled: true,
  },
  {
    id: "base",
    chainId: "0x2105",
    name: "Base",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_base.jpg",
    rpc: ["https://mainnet.base.org", "https://base.llamarpc.com", "https://base.publicnode.com"],
    explorer: "https://basescan.org",
    moralisChain: "base",
    covalentChainId: 8453,
    enabled: true,
  },
  {
    id: "avalanche",
    chainId: "0xa86a",
    name: "Avalanche C-Chain",
    symbol: "AVAX",
    type: ChainType.EVM,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/avax.png",
    rpc: ["https://api.avax.network/ext/bc/C/rpc", "https://avalanche.publicnode.com", "https://avax.meowrpc.com"],
    explorer: "https://snowtrace.io",
    moralisChain: "avalanche",
    covalentChainId: 43114,
    enabled: true,
  },
  {
    id: "fantom",
    chainId: "0xfa",
    name: "Fantom",
    symbol: "FTM",
    type: ChainType.EVM,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/ftm.png",
    rpc: ["https://rpc.ftm.tools", "https://fantom.publicnode.com", "https://rpc.ankr.com/fantom"],
    explorer: "https://ftmscan.com",
    moralisChain: "fantom",
    covalentChainId: 250,
    enabled: true,
  },
  {
    id: "cronos",
    chainId: "0x19",
    name: "Cronos",
    symbol: "CRO",
    type: ChainType.EVM,
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png",
    rpc: ["https://evm.cronos.org", "https://cronos-evm.publicnode.com"],
    explorer: "https://cronoscan.com",
    moralisChain: "cronos",
    covalentChainId: 25,
    enabled: true,
  },
  {
    id: "gnosis",
    chainId: "0x64",
    name: "Gnosis Chain",
    symbol: "xDAI",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_gnosis.jpg",
    rpc: ["https://rpc.gnosischain.com", "https://gnosis.publicnode.com"],
    explorer: "https://gnosisscan.io",
    moralisChain: "gnosis",
    covalentChainId: 100,
    enabled: true,
  },
  {
    id: "moonbeam",
    chainId: "0x504",
    name: "Moonbeam",
    symbol: "GLMR",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_moonbeam.jpg",
    rpc: ["https://rpc.api.moonbeam.network", "https://moonbeam.publicnode.com"],
    explorer: "https://moonscan.io",
    moralisChain: "moonbeam",
    covalentChainId: 1284,
    enabled: true,
  },
  {
    id: "moonriver",
    chainId: "0x505",
    name: "Moonriver",
    symbol: "MOVR",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_moonriver.jpg",
    rpc: ["https://rpc.api.moonriver.moonbeam.network", "https://moonriver.publicnode.com"],
    explorer: "https://moonriver.moonscan.io",
    covalentChainId: 1285,
    enabled: true,
  },
  {
    id: "celo",
    chainId: "0xa4ec",
    name: "Celo",
    symbol: "CELO",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_celo.jpg",
    rpc: ["https://forno.celo.org", "https://celo.publicnode.com"],
    explorer: "https://celoscan.io",
    covalentChainId: 42220,
    enabled: true,
  },
  {
    id: "aurora",
    chainId: "0x4e454152",
    name: "Aurora",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_aurora.jpg",
    rpc: ["https://mainnet.aurora.dev"],
    explorer: "https://aurorascan.dev",
    covalentChainId: 1313161554,
    enabled: true,
  },
  {
    id: "harmony",
    chainId: "0x63564c40",
    name: "Harmony",
    symbol: "ONE",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_harmony.jpg",
    rpc: ["https://api.harmony.one", "https://harmony-0.drpc.org"],
    explorer: "https://explorer.harmony.one",
    covalentChainId: 1666600000,
    enabled: true,
  },
  {
    id: "zkSync",
    chainId: "0x144",
    name: "zkSync Era",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_zksync.jpg",
    rpc: ["https://mainnet.era.zksync.io", "https://zksync.drpc.org"],
    explorer: "https://explorer.zksync.io",
    covalentChainId: 324,
    enabled: true,
  },
  {
    id: "linea",
    chainId: "0xe708",
    name: "Linea",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_linea.jpg",
    rpc: ["https://rpc.linea.build", "https://linea.drpc.org"],
    explorer: "https://lineascan.build",
    covalentChainId: 59144,
    enabled: true,
  },
  {
    id: "scroll",
    chainId: "0x82750",
    name: "Scroll",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_scroll.jpg",
    rpc: ["https://rpc.scroll.io", "https://scroll.drpc.org"],
    explorer: "https://scrollscan.com",
    covalentChainId: 534352,
    enabled: true,
  },
  {
    id: "polygon-zkevm",
    chainId: "0x44d",
    name: "Polygon zkEVM",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_polygon_zkevm.jpg",
    rpc: ["https://zkevm-rpc.com", "https://polygon-zkevm.drpc.org"],
    explorer: "https://zkevm.polygonscan.com",
    covalentChainId: 1101,
    enabled: true,
  },
  {
    id: "mantle",
    chainId: "0x1388",
    name: "Mantle",
    symbol: "MNT",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_mantle.jpg",
    rpc: ["https://rpc.mantle.xyz"],
    explorer: "https://explorer.mantle.xyz",
    covalentChainId: 5000,
    enabled: true,
  },
  {
    id: "metis",
    chainId: "0x440",
    name: "Metis",
    symbol: "METIS",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_metis.jpg",
    rpc: ["https://andromeda.metis.io/?owner=1088"],
    explorer: "https://andromeda-explorer.metis.io",
    covalentChainId: 1088,
    enabled: true,
  },
  {
    id: "kava",
    chainId: "0x8ae",
    name: "Kava EVM",
    symbol: "KAVA",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_kava.jpg",
    rpc: ["https://evm.kava.io", "https://kava-evm.publicnode.com"],
    explorer: "https://kavascan.com",
    covalentChainId: 2222,
    enabled: true,
  },
  {
    id: "klaytn",
    chainId: "0x2019",
    name: "Klaytn",
    symbol: "KLAY",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_klaytn.jpg",
    rpc: ["https://public-en-cypress.klaytn.net"],
    explorer: "https://scope.klaytn.com",
    covalentChainId: 8217,
    enabled: true,
  },
  {
    id: "boba",
    chainId: "0x120",
    name: "Boba Network",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_boba.jpg",
    rpc: ["https://mainnet.boba.network"],
    explorer: "https://bobascan.com",
    covalentChainId: 288,
    enabled: true,
  },
  {
    id: "fuse",
    chainId: "0x7a",
    name: "Fuse",
    symbol: "FUSE",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_fuse.jpg",
    rpc: ["https://rpc.fuse.io"],
    explorer: "https://explorer.fuse.io",
    covalentChainId: 122,
    enabled: true,
  },
  {
    id: "evmos",
    chainId: "0x2329",
    name: "Evmos",
    symbol: "EVMOS",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_evmos.jpg",
    rpc: ["https://eth.bd.evmos.org:8545"],
    explorer: "https://escan.live",
    covalentChainId: 9001,
    enabled: true,
  },
  {
    id: "okx",
    chainId: "0x42",
    name: "OKX Chain",
    symbol: "OKT",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_okex.jpg",
    rpc: ["https://exchainrpc.okex.org"],
    explorer: "https://www.oklink.com/okc",
    covalentChainId: 66,
    enabled: true,
  },
  {
    id: "heco",
    chainId: "0x80",
    name: "Huobi ECO Chain",
    symbol: "HT",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_heco.jpg",
    rpc: ["https://http-mainnet.hecochain.com"],
    explorer: "https://hecoinfo.com",
    covalentChainId: 128,
    enabled: true,
  },
  {
    id: "arbitrum-nova",
    chainId: "0xa4ba",
    name: "Arbitrum Nova",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_arbitrum_nova.jpg",
    rpc: ["https://nova.arbitrum.io/rpc"],
    explorer: "https://nova.arbiscan.io",
    covalentChainId: 42170,
    enabled: true,
  },
  {
    id: "core",
    chainId: "0x45c",
    name: "Core Blockchain",
    symbol: "CORE",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_core.jpg",
    rpc: ["https://rpc.coredao.org"],
    explorer: "https://scan.coredao.org",
    enabled: true,
  },
  {
    id: "opbnb",
    chainId: "0xcc",
    name: "opBNB",
    symbol: "BNB",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_opbnb.jpg",
    rpc: ["https://opbnb-mainnet-rpc.bnbchain.org"],
    explorer: "https://opbnbscan.com",
    covalentChainId: 204,
    enabled: true,
  },

  // ========== NON-EVM CHAINS ==========
  
  {
    id: "solana",
    chainId: "solana-mainnet",
    name: "Solana",
    symbol: "SOL",
    type: ChainType.SOLANA,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/sol.png",
    rpc: ["https://api.mainnet-beta.solana.com", "https://solana-api.projectserum.com"],
    explorer: "https://explorer.solana.com",
    enabled: true,
  },
  {
    id: "ton",
    chainId: "ton-mainnet",
    name: "TON",
    symbol: "TON",
    type: ChainType.TON,
    logo: "https://ton.org/download/ton_symbol.png",
    rpc: ["https://toncenter.com/api/v2/jsonRPC"],
    explorer: "https://tonscan.org",
    enabled: true,
  },
  {
    id: "cosmos",
    chainId: "cosmoshub-4",
    name: "Cosmos Hub",
    symbol: "ATOM",
    type: ChainType.COSMOS,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/atom.png",
    rpc: ["https://cosmos-rpc.polkachu.com", "https://rpc-cosmoshub.whispernode.com"],
    explorer: "https://www.mintscan.io/cosmos",
    enabled: true,
  },
  {
    id: "osmosis",
    chainId: "osmosis-1",
    name: "Osmosis",
    symbol: "OSMO",
    type: ChainType.COSMOS,
    logo: "https://raw.githubusercontent.com/osmosis-labs/assetlists/main/images/osmo.png",
    rpc: ["https://osmosis-rpc.polkachu.com", "https://rpc-osmosis.whispernode.com"],
    explorer: "https://www.mintscan.io/osmosis",
    enabled: true,
  },
  {
    id: "juno",
    chainId: "juno-1",
    name: "Juno",
    symbol: "JUNO",
    type: ChainType.COSMOS,
    logo: "https://raw.githubusercontent.com/cosmos/chain-registry/master/juno/images/juno.png",
    rpc: ["https://juno-rpc.polkachu.com"],
    explorer: "https://www.mintscan.io/juno",
    enabled: true,
  },
  {
    id: "terra",
    chainId: "phoenix-1",
    name: "Terra",
    symbol: "LUNA",
    type: ChainType.COSMOS,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/luna.png",
    rpc: ["https://terra-rpc.polkachu.com"],
    explorer: "https://finder.terra.money",
    enabled: true,
  },
  {
    id: "injective",
    chainId: "injective-1",
    name: "Injective",
    symbol: "INJ",
    type: ChainType.COSMOS,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/inj.png",
    rpc: ["https://injective-rpc.polkachu.com"],
    explorer: "https://explorer.injective.network",
    enabled: true,
  },
  {
    id: "sei",
    chainId: "pacific-1",
    name: "Sei",
    symbol: "SEI",
    type: ChainType.COSMOS,
    logo: "https://raw.githubusercontent.com/cosmos/chain-registry/master/sei/images/sei.png",
    rpc: ["https://sei-rpc.polkachu.com"],
    explorer: "https://www.seiscan.app",
    enabled: true,
  },
  {
    id: "celestia",
    chainId: "celestia",
    name: "Celestia",
    symbol: "TIA",
    type: ChainType.COSMOS,
    logo: "https://raw.githubusercontent.com/cosmos/chain-registry/master/celestia/images/celestia.png",
    rpc: ["https://celestia-rpc.polkachu.com"],
    explorer: "https://www.mintscan.io/celestia",
    enabled: true,
  },
  {
    id: "tron",
    chainId: "tron-mainnet",
    name: "TRON",
    symbol: "TRX",
    type: ChainType.TRON,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/trx.png",
    rpc: ["https://api.trongrid.io"],
    explorer: "https://tronscan.org",
    enabled: true,
  },
  {
    id: "near",
    chainId: "near-mainnet",
    name: "NEAR Protocol",
    symbol: "NEAR",
    type: ChainType.NEAR,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/near.png",
    rpc: ["https://rpc.mainnet.near.org"],
    explorer: "https://explorer.near.org",
    enabled: true,
  },
  {
    id: "aptos",
    chainId: "aptos-mainnet",
    name: "Aptos",
    symbol: "APT",
    type: ChainType.APTOS,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/apt.png",
    rpc: ["https://fullnode.mainnet.aptoslabs.com/v1"],
    explorer: "https://explorer.aptoslabs.com",
    enabled: true,
  },
  {
    id: "sui",
    chainId: "sui-mainnet",
    name: "Sui",
    symbol: "SUI",
    type: ChainType.SUI,
    logo: "https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/sui.png",
    rpc: ["https://fullnode.mainnet.sui.io:443"],
    explorer: "https://explorer.sui.io",
    enabled: true,
  },
  {
    id: "starknet",
    chainId: "0x534e5f4d41494e",
    name: "Starknet",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_starknet.jpg",
    rpc: ["https://starknet-mainnet.public.blastapi.io"],
    explorer: "https://starkscan.co",
    enabled: true,
  },
  {
    id: "zeta",
    chainId: "0x1b59",
    name: "ZetaChain",
    symbol: "ZETA",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_zetachain.jpg",
    rpc: ["https://zetachain-evm.blockpi.network/v1/rpc/public"],
    explorer: "https://explorer.zetachain.com",
    enabled: true,
  },
  {
    id: "blast",
    chainId: "0x13e31",
    name: "Blast",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_blast.jpg",
    rpc: ["https://rpc.blast.io"],
    explorer: "https://blastscan.io",
    enabled: true,
  },
  {
    id: "mode",
    chainId: "0x868b",
    name: "Mode Network",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_mode.jpg",
    rpc: ["https://mainnet.mode.network"],
    explorer: "https://explorer.mode.network",
    enabled: true,
  },
  {
    id: "manta",
    chainId: "0xa9",
    name: "Manta Pacific",
    symbol: "ETH",
    type: ChainType.EVM,
    logo: "https://icons.llamao.fi/icons/chains/rsz_manta.jpg",
    rpc: ["https://pacific-rpc.manta.network/http"],
    explorer: "https://pacific-explorer.manta.network",
    enabled: true,
  },
]

// Helper functions
export const getChainById = (id: string): ChainConfig | undefined => {
  return CHAIN_CONFIGS.find(chain => chain.id === id)
}

export const getChainByChainId = (chainId: string | number): ChainConfig | undefined => {
  return CHAIN_CONFIGS.find(chain => chain.chainId === chainId)
}

export const getChainsByType = (type: ChainType): ChainConfig[] => {
  return CHAIN_CONFIGS.filter(chain => chain.type === type && chain.enabled)
}

export const getAllEnabledChains = (): ChainConfig[] => {
  return CHAIN_CONFIGS.filter(chain => chain.enabled)
}

export const getEVMChains = (): ChainConfig[] => {
  return getChainsByType(ChainType.EVM)
}

export const getNonEVMChains = (): ChainConfig[] => {
  return CHAIN_CONFIGS.filter(chain => chain.type !== ChainType.EVM && chain.enabled)
}

